version: '3'
services:
  app:
   build: .
   container_name: llm-backend 
   #command: gunicorn main:app --bind "[::]:5555" -k uvicorn.workers.UvicornWorker   
   stdin_open: true # docker run -i
   tty: true        # docker run -t 
   ports:
    - 5555:5555
   volumes:
    - .:/app
   depends_on:
    - weaviate
  weaviate:
    container_name: weaviate
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.19.3
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      OPENAI_APIKEY: $OPENAI_API_KEY
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ./weaviate:/var/lib/weaviate